export const settings = {
  coverageTargetDays: 7,
  freezerCapacityBoxes: 24,
};

export const products = [
  {
    id: "butter",
    name: "Butter Croissant Dough",
    pastryName: "Butter Croissant",
    zoneId: "laminated",
    piecesPerBox: 60,
    costPerBox: 30,
    fullBoxes: 6,
    partialPieces: 30,
    incomingBoxes: 0,
    typicalDailySales: 31,
    expectedUsageUntilNextOrder: 310,
    minimumOrderBoxes: 1,
    comparableDays: [29, 33, 30, 32],
  },
  {
    id: "chocolate",
    name: "Chocolate Croissant Dough",
    pastryName: "Chocolate Croissant",
    zoneId: "laminated",
    piecesPerBox: 48,
    costPerBox: 28,
    fullBoxes: 2,
    partialPieces: 12,
    incomingBoxes: 0,
    typicalDailySales: 22,
    expectedUsageUntilNextOrder: 154,
    minimumOrderBoxes: 2,
    comparableDays: [20, 23, 21, 24],
  },
  {
    id: "almond",
    name: "Almond Croissant Dough",
    pastryName: "Almond Croissant",
    zoneId: "laminated",
    piecesPerBox: 36,
    costPerBox: 32,
    fullBoxes: 4,
    partialPieces: 0,
    incomingBoxes: 0,
    typicalDailySales: 15,
    expectedUsageUntilNextOrder: 105,
    minimumOrderBoxes: 1,
    comparableDays: [16, 14, 15, 15],
  },
  {
    id: "ham",
    name: "Ham & Cheese Dough",
    pastryName: "Ham & Cheese",
    zoneId: "savory",
    piecesPerBox: 40,
    costPerBox: 35,
    fullBoxes: 1,
    partialPieces: 20,
    incomingBoxes: 0,
    typicalDailySales: 20,
    expectedUsageUntilNextOrder: 140,
    minimumOrderBoxes: 1,
    comparableDays: [18, 21, 20, 19],
  },
];

export const wasteRecords = [
  {
    id: "butter",
    pastryName: "Butter Croissant",
    leftoverUnits: 12,
    supplierCostPerUnit: 0.5,
    currentProduction: 38,
    suggestedProduction: 34,
    comparableWaste: [8, 10, 9, 12],
    soldOutComparableDays: 0,
    evidence: ["Leftovers appeared on four comparable Tuesdays", "No sellouts or emergency extra batches recorded", "Tuesday traffic was within the sample normal range"],
  },
  {
    id: "chocolate",
    pastryName: "Chocolate Croissant",
    leftoverUnits: 7,
    supplierCostPerUnit: 0.58,
    currentProduction: 28,
    suggestedProduction: 26,
    comparableWaste: [4, 5, 6, 7],
    soldOutComparableDays: 1,
    evidence: ["Waste increased across recent comparable Tuesdays", "One sellout was recorded, so a small buffer remains", "Sample POS sales were stable"],
  },
  {
    id: "almond",
    pastryName: "Almond Croissant",
    leftoverUnits: 4,
    supplierCostPerUnit: 0.89,
    currentProduction: 20,
    suggestedProduction: 19,
    comparableWaste: [2, 5, 3, 4],
    soldOutComparableDays: 0,
    evidence: ["Small repeated leftovers on comparable Tuesdays", "No sellouts recorded", "Recommendation keeps a sample end-of-day buffer"],
  },
  {
    id: "ham",
    pastryName: "Ham & Cheese",
    leftoverUnits: 3,
    supplierCostPerUnit: 0.88,
    currentProduction: 24,
    suggestedProduction: 24,
    comparableWaste: [1, 2, 1, 3],
    soldOutComparableDays: 2,
    evidence: ["Two sellouts were recorded on comparable Tuesdays", "Current leftovers may reflect an unusual day", "No reduction suggested until the manager reviews context"],
  },
];

export const productionPlan = [
  { id: "butter", pastryName: "Butter Croissant", currentQuantity: 38, suggestedQuantity: 34, availability: "Low risk", evidence: "Repeated Tuesday leftovers · no sellouts" },
  { id: "chocolate", pastryName: "Chocolate Croissant", currentQuantity: 28, suggestedQuantity: 26, availability: "Review", evidence: "Waste rising · one comparable sellout" },
  { id: "almond", pastryName: "Almond Croissant", currentQuantity: 20, suggestedQuantity: 19, availability: "Low risk", evidence: "Small repeated leftovers · no sellouts" },
  { id: "ham", pastryName: "Ham & Cheese", currentQuantity: 24, suggestedQuantity: 24, availability: "Review", evidence: "Two comparable sellouts · hold current quantity" },
  { id: "garlic", pastryName: "Garlic Cream Cheese", currentQuantity: 34, suggestedQuantity: 34, availability: "Low risk", evidence: "Within sample normal range" },
  { id: "blueberry", pastryName: "Blueberry Cream Cheese", currentQuantity: 30, suggestedQuantity: 30, availability: "Low risk", evidence: "Within sample normal range" },
];

export const freezerZones = [
  { id: "laminated", name: "Laminated dough", contents: "Butter, chocolate, and almond dough", currentUnits: 14, practicalCapacity: 16, hardCapacity: 18 },
  { id: "savory", name: "Savory dough", contents: "Ham & cheese and savory dough", currentUnits: 6, practicalCapacity: 7, hardCapacity: 8 },
  { id: "desserts", name: "Packaged desserts", contents: "Macarons and packaged desserts", currentUnits: 7, practicalCapacity: 9, hardCapacity: 10 },
  { id: "mixes", name: "Mixes & fillings", contents: "Cake batter, smoothie mixes, and fillings", currentUnits: 8, practicalCapacity: 10, hardCapacity: 12 },
];

export const topPastries = [
  ["Butter Croissant", 31, "butter"],
  ["Garlic Cream Cheese", 28],
  ["Blueberry Cream Cheese", 26],
  ["Chocolate Croissant", 22, "chocolate"],
  ["Ham & Cheese", 20, "ham"],
  ["Red Bean Bread", 18],
  ["Strawberry Croissant", 17],
  ["Almond Croissant", 15, "almond"],
  ["Curry Croquette", 14],
  ["Sweet Rice Donut", 13],
];
